SELECT * FROM financial_loan

--- TOTAL LOAN APPLICATION
SELECT COUNT(id) FROM financial_loan

--- MTD TOTAL LOAN APPLICATION
SELECT COUNT(ID) AS MTD_TOTAL_LOAN_APPLICATION FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 12

--- PMTD TOTAL LOAN APPLICATION
SELECT COUNT(ID) AS PMTD_TOTAL_LOAN_APPLICATION FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 11

-- TOTAL FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT FROM financial_loan

--MTD TOTAL FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS MTD_TOTAL_FUNDED_AMOUNT FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 12

--- PMTD TOTAL FUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS PMTD_TOTAL_FUNDED_AMOUNT FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 11

--- TOTAL AMOUNT RECEIVED
SELECT SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED FROM financial_loan

--- MTD TOTAL AMOUNT RECEIVED
SELECT SUM(TOTAL_PAYMENT) AS MTD_TOTAL_AMOUNT_RECEIVED FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 12

--- MTD TOTAL AMOUNT RECEIVED
SELECT SUM(TOTAL_PAYMENT) AS PMTD_TOTAL_AMOUNT_RECEIVED FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 11

-- AVERAGE INTEREST RATE
SELECT AVG(INT_RATE)*100 AS AVERAGE_INTEREST_RATE FROM financial_loan

-- MTD AVERAGE INTEREST RATE
SELECT AVG(INT_RATE) *100 AS MTD_AVERAGE_INTEREST_RATE FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 12

-- PMTD AVERAGE INTEREST RATE
SELECT AVG(INT_RATE) *100 AS PMTD_AVERAGE_INTEREST_RATE FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 11

-- AVERAGE DEBT TO INCOME RATIO
SELECT AVG(DTI)* 100 AS AVERAGE_DEBT_TO_INCOME_RATIO  FROM financial_loan

--MTD AVERAGE DEBT TO INCOME RATIO
SELECT AVG(DTI) * 100 AS MTD_AVERAGE_DEBT_INCOME_RATIO FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 12

--PMTD AVERAGE DEBT TO INCOME RATIO
SELECT AVG(DTI)* 100 AS PMTD_AVERAGE_DEBT_INCOME_RATIO FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 11

--GOOD LOAN
-- GOOD LOAN APPLICATION PERCENTAGE
SELECT
	(COUNT(CASE WHEN LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current' THEN ID 
	END) * 100) / COUNT(ID) AS GOOD_LOAN_APPLICATION_PERCENTAGE
	FROM financial_loan
	
--- GOOD LOAN APPLICATION
SELECT COUNT(ID) AS GOOD_LOAN_APPLICATION FROM financial_loan
WHERE loan_status = 'Fully Paid' OR loan_status = 'Current'

-- GOOD LOAN FOUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS GOOD_LOAN_FOUNDED_AMOUNT FROM financial_loan
WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current'

 -- TOTAL RECEIVED AMOUNT
 SELECT SUM(TOTAL_PAYMENT) AS TOTAL_RECEIVED_AMOUNT FROM financial_loan
 WHERE LOAN_STATUS = 'Fully Paid' OR LOAN_STATUS = 'Current'

 --BAD LOAN
 --BAD LOAN PERCENTAGE
 SELECT (COUNT(CASE WHEN LOAN_STATUS = 'charged Off' THEN ID 
 END) * 100.0) / COUNT(ID) AS BAD_LOAN_PERCENTAGE
 FROM financial_loan

 -- BAD LOAN APPLICATION
 SELECT COUNT(ID) AS BAD_LOAN_APPLICATION
 FROM financial_loan
 WHERE LOAN_STATUS = 'Charged Off'

-- BAD LOAN FOUNDED AMOUNT
SELECT SUM(LOAN_AMOUNT) AS BAD_LOAN_FOUNDED_AMOUNT
FROM financial_loan
WHERE LOAN_STATUS = 'Charged Off'

-- BAD LOAN RECEIVED
SELECT SUM(TOTAL_PAYMENT) AS BAD_LOAN_RECEIVED
FROM financial_loan
WHERE LOAN_STATUS = 'Charged Off'

-- LOAN STATUS
SELECT
LOAN_STATUS,
COUNT(ID) AS TOTAL_LOAD_APPLICATION,
SUM(LOAN_AMOUNT) AS tOTAL_LOAN_FOUNDED,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED,
AVG(INT_RATE)*100 AS AVERAGE_INTEREST_RATE,
AVG(DTI) * 100 AS AVERAGE_DEBIT_TO_INCOME
FROM financial_loan
GROUP BY LOAN_STATUS


SELECT LOAN_STATUS,
SUM(LOAN_AMOUNT) AS MTD_FOUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS MTD_TOTA_PAYMENT
FROM financial_loan
WHERE MONTH(ISSUE_DATE) = 12
GROUP BY LOAN_STATUS



--- MONTHLY TREND BY ISSUE DATE
SELECT 
MONTH(ISSUE_DATE) AS MONTH_Number,
DATENAME (MONTH, ISSUE_DATE) AS MONTH_NAME,
COUNT(ID) AS TOTAL_LOAN_APPLICATION,
SUM(LOAN_AMOUNT) AS TOTAL_AMOUNT_FOUNDED,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM financial_loan
GROUP BY MONTH(ISSUE_DATE), DATENAME (MONTH, ISSUE_DATE)
ORDER BY MONTH(ISSUE_DATE), DATENAME (MONTH, ISSUE_DATE)

--STATE
SELECT 
ADDRESS_STATE AS STATE,
COUNT(ID) AS TOTAL_LOAN,
SUM(LOAN_AMOUNT) AS TOTAL_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM financial_loan
GROUP BY ADDRESS_STATE
ORDER BY ADDRESS_STATE

--LOAN TERM
SELECT 
ADDRESS_STATE AS STATE,
COUNT(ID) AS TOTAL_LOAN,
SUM(LOAN_AMOUNT) AS TOTAL_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM financial_loan
GROUP BY ADDRESS_STATE
ORDER BY ADDRESS_STATE

--LOAN TERM
SELECT TERM AS LOANTERM,
COUNT(ID) AS TOTAL_LOAN,
SUM(LOAN_AMOUNT) AS TOTAL_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM financial_loan
GROUP BY TERM
ORDER BY TERM

--EMPLOYMENT_LENGTH
SELECT
EMP_LENGTH AS EMPLOYMENT_LENGTH,
COUNT(ID) AS TOTAL_LOAN,
SUM(LOAN_AMOUNT) AS TOTAL_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM financial_loan
GROUP BY EMP_LENGTH 
ORDER BY EMP_LENGTH 

--LOAN PURPOSE
SELECT 
PURPOSE AS LOAN_PURPOSE
COUNT(ID) AS TOTAL_LOAN_APPLICATION,
SUM(LOAN_AMOUNT)AS TOTAL_FOUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM financial_loan
GROUP BY PURPOSE
ORDER BY PURPOSE

--HOME OWNERSHIP
SELECT
HOME_OWNERSHIP AS HOME_OWNERSHIP,
COUNT(ID) AS TOTAL_LOAN_APPLICATION,
SUM(LOAN_AMOUNT)AS TOTAL_FOUNDED_AMOUNT,
SUM(TOTAL_PAYMENT) AS TOTAL_AMOUNT_RECEIVED
FROM financial_loan
GROUP BY HOME_OWNERSHIP
ORDER BY HOME_OWNERSHIP